version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: dev-mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    environment:
      CB_ADMIN_NAME: cbadmin
      CB_ADMIN_PASSWORD: ${CB_PASS}
    ports:
      - "8978:8978"
    depends_on:
      - mysql
    restart: always
    env_file:
      - .env

volumes:
  mysql_data:
